# Generated by Django 6.1 on 2026-09-22 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0003_lesson_grade_schedule_lesson_schedule_attendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid'), ('paid', 'Paid')], default='unpaid', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_periods', to='education.enrollment')),
            ],
            options={
                'db_table': 'billing_billingperiod',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.billingperiod')),
                ('registered_by', models.ForeignKey(help_text='Кто из админов внёс платёж вручную.', on_delete=django.db.models.deletion.PROTECT, related_name='payments_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_payment',
            },
        ),
        migrations.AddConstraint(
            model_name='billingperiod',
            constraint=models.UniqueConstraint(fields=('enrollment', 'period_start', 'period_end'), name='uniq_billingperiod_enrollment_period'),
        ),
        migrations.AddConstraint(
            model_name='billingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('amount_due__gte', 0)), name='billingperiod_amount_due_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
    ]
