# Generated by Django 6.1 on 2026-09-22 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_enrollment_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('room', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('held', 'Held'), ('cancelled', 'Cancelled')], default='planned', max_length=16)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(help_text='Денормализовано — снимок на момент создания занятия.', on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='education.subject')),
                ('teacher', models.ForeignKey(help_text='Денормализовано — снимок на момент создания занятия.', on_delete=django.db.models.deletion.PROTECT, related_name='lessons_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'education_lesson',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=16)),
                ('max_value', models.CharField(blank=True, max_length=16, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('given_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='education.enrollment')),
                ('given_by_teacher', models.ForeignKey(help_text='Исторический snapshot — кто РЕАЛЬНО поставил оценку, независимо от того, кто сейчас Group.teacher.', on_delete=django.db.models.deletion.PROTECT, related_name='grades_given', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, help_text='NULL — если оценка не привязана к конкретному занятию (например, итоговая).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='education.lesson')),
            ],
            options={
                'db_table': 'education_grade',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=64, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='education.enrollment')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='education.group')),
            ],
            options={
                'db_table': 'education_schedule',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='education.schedule'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=16)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_marked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='education.student')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='education.lesson')),
            ],
            options={
                'db_table': 'education_attendance',
                'constraints': [models.UniqueConstraint(fields=('lesson', 'student'), name='uniq_attendance_lesson_student')],
            },
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('enrollment__isnull', True), ('group__isnull', False)), models.Q(('enrollment__isnull', False), ('group__isnull', True)), _connector='OR'), name='schedule_group_xor_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('schedule', 'starts_at'), name='uniq_lesson_schedule_starts_at'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='lesson_ends_after_starts'),
        ),
    ]
