# Generated by Django 6.1 on 2026-09-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Заполняется при привязке через InviteCode (Telegram User Linking).', null=True),
        ),
    ]
